### ISSUE TITLE
Enh: generalize cube at each back_prop()

### ISSUE THREAD

**Issue by jmzhao** [jmzhao/CS704-asn3#1]
Cubes in PDR.back_prop() are obtained from counterexamples given by z3.Solver(). Now we observe cubes are usually (implicationally) minimal. We could generalize it before back_prop it further.

**Comment by jmzhao** [comment]
Now running for all test cases except marginal-algebra-unsafe. Still not sure why.

Last lines of Error message:

```
DEBUG:root:  check_res=0
DEBUG:root:  nR0s=None
DEBUG:root:  ce_seq=[{f: None, b: False, a: False, d: True, c: False, e: True}, {f: False, b: True, a: False, d: False, c: False, e: False}]
Traceback (most recent call last):
  File ".\pdr\debug.py", line 11, in <module>
    test.test([test.test_cases.get_by(name="marginal-algebra-unsafe")])
  File ".\pdr\test.py", line 44, in test
    check_res, inv, ce_seq = pdr.pdr(case['init'], case['trans'], case['post'])
  File ".\pdr.py", line 311, in pdr
    check_res, nRs, ce_seq = self.back_prop(Rs, init, trans, post)
  File ".\pdr.py", line 222, in back_prop
    check_res, nR0s, ce_seq = self.back_prop(R0s, init, trans, And(*Rn), level+1)
  File ".\pdr.py", line 218, in back_prop
    lambda cube : self.back_prop(R0s, init, trans, And(Not(cube), *Rn), level+1)[0] == SAFE)
  File ".\pdr.py", line 87, in generalize_cube
    tester=lambda l : cube_tester(And(*l)))
  File ".\pdr\util.py", line 14, in generalize
    return generalize(new_l, tester)
  File ".\pdr\util.py", line 14, in generalize
    return generalize(new_l, tester)
  File ".\pdr\util.py", line 14, in generalize
    return generalize(new_l, tester)
  File ".\pdr\util.py", line 14, in generalize
    return generalize(new_l, tester)
  File ".\pdr\util.py", line 14, in generalize
    return generalize(new_l, tester)
  File ".\pdr\util.py", line 13, in generalize
    if tester(new_l) :
  File ".\pdr.py", line 87, in <lambda>
    tester=lambda l : cube_tester(And(*l)))
  File ".\pdr.py", line 218, in <lambda>
    lambda cube : self.back_prop(R0s, init, trans, And(Not(cube), *Rn), level+1)[0] == SAFE)
  File ".\pdr.py", line 235, in back_prop
    R0s[-1] = R0s[-1] + [Not(cube_prev)]
IndexError: list index out of range
```
